# Generated by Django 4.1 on 2022-09-04 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(default="", max_length=10000)),
                ("fecha_de_creacion", models.DateField(default=datetime.date.today)),
                ("fecha_entrega", models.DateField(default=datetime.date.today)),
                ("usuario_responsable", models.CharField(default="", max_length=128)),
                (
                    "estado_dela_tarea",
                    models.CharField(default="PROGRESO", max_length=32),
                ),
            ],
        ),
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="", max_length=128)),
                ("papellido", models.CharField(default="", max_length=128)),
                ("codigo_usuario", models.CharField(default="", max_length=128)),
                ("contrasenia", models.CharField(default="", max_length=128)),
            ],
        ),
    ]
